name: homespot
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  
  # State management
  provider: ^6.1.1
  
  # HTTP & Storage
  http: ^1.2.0
  flutter_secure_storage: ^9.0.0
  
  # Navigation
  go_router: ^13.2.0
  
  # Image
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7
  
  # UI
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

